---
title: "Microarray data: Inspection"
author: "Axel Nohturfft"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    code_folding: "hide"
---


<style>
h1 {background: brown;color: white;padding-left: 7px;}
h2 {background: grey;color: white;padding-left: 7px;}
h3 {color: brown;}
code {color: chocolate;}
details p {font-family: monospace;}
</style>

## BDiB Session 04-March-2021  

```{r load packages, warning=FALSE, message=FALSE}
source("packages.R")
```


### Download data    
```{r download soft file}
dest.file <- "GSE26868_series_matrix.txt.gz"
if (!file.exists(dest.file)) {
  download.file(url=paste0(
    "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE26nnn",
    "/GSE26868/matrix/GSE26868_series_matrix.txt.gz"
  ),
  destfile = dest.file)
}
```


```{r file-name, results="asis"}
cat("Data file:<b>", dest.file, "</b>")
```


```{r open file, results="hide"}
gse <- GEOquery::getGEO(filename = dest.file, GSEMatrix=TRUE)
```

### Check what data class has been generated:  
```{r}
class(gse)
```

#### Probe IDs (print a few):
```{r}
head(Biobase::featureNames(gse))
```

```{r}
Biobase::pData(gse)[,c("title", "source_name_ch1")] %>% knitr::kable(.)
```


### Meta info about the data series:  
```{r print meta info, results="asis"}
details::details(GEOquery::Meta(gse), lang=NULL, summary="Show meta info")
```