---
title: "Microarray data: Inspection"
author: "Axel Nohturfft"
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
    code_folding: "hide"
---


<style>
h1 {background: brown;color: white;padding-left: 7px;}
h2 {background: grey;color: white;padding-left: 7px;}
h3 {color: brown;}
code {color: chocolate;}
details p {font-family: monospace;}
</style>

## BDiB Session 04-March-2021  

```{r load packages, warning=FALSE, message=FALSE}
source("packages.R")
```


### Download data    
```{r download soft file}
dest.file <- "GSE26868_family.soft.gz"
if (!file.exists(dest.file)) {
  download.file(url=paste0(
    "ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE26nnn/",
    "GSE26868/soft/GSE26868_family.soft.gz"
  ),
  destfile = dest.file)
}
```


```{r file-name, results="asis"}
cat("Data file:<b>", dest.file, "</b>")
```



```{r open file, results="hide"}
gse <- GEOquery::getGEO(filename = dest.file)
```
### Meta info about the data series:  
```{r print meta info, results="asis"}
details::details(GEOquery::Meta(gse), lang=NULL, summary="Show meta info")
```

### GEO sample IDs always start with 'GSM':  
'GSM...' = GEO sample.  
```{r results="asis"}
# Using the GEOquery::GSMList() function to obtain sample IDs
cat(paste(names(GEOquery::GSMList(gse)), collapse=", "))
```

### Check that only one technology (=platform) was used for the data:  
'GPL...' = GEO platform.  
```{r}
names(GEOquery::GPLList(gse))
```

```{r}
help(package="Biobase")
e <- Biobase::exprs(gse)
class(gse)
```

